### ISSUE TITLE
Module not compatible with php-http/httplug ^2.0

### ISSUE THREAD

**Issue by bheindl** [netresearch/dhl-sdk-api-parcel-management#1]
Current state of the module is not compatible with the current php-http/httplug version. Since more and more libraries already switched to the new version of php-http/httplug, this module is not usable anymore in environments, where the new version of php-http/httplug is required from other libraries. Can this module be updated to require php-http/httplug ^2.0?

**Comment by mam08ixo** [comment]
We have a legacy use case for this API SDK which does not allow us to upgrade to HTTPlug v2. As soon as we can drop support for the legacy environment, SDKs will be upgraded.

In the meantime, feel free to maintain a fork with HTTPlug v2 compatibility.
