### ISSUE TITLE
Update jsonmapper

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-sdk-api-parcel-management#2]
the package is using an old version of the jsonmapper 1.4.0.
Thee jsonmapper is available in 4.0.0 now. Not the company fork, the original from the employee ;-)
Would be a good thing, to keep the own packages up-to-date.

I am using the 4.0.0 in other client and this is a problem now.

**Comment by mam08ixo** [comment]
We can update the package in our libraries but do not expect a release before Magento 2.4.4 was published.

**Comment by ngolatka** [comment]
Dependency has been updated, closing this issue.
